version: 2.1

executors:
  node-executor:
    docker:
      - image: cypress/base:18.16.0 # Use a Cypress-compatible Docker image with Node.js preinstalled

jobs:
  cypress-tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Cypress tests
          command: npx cypress run --browser chrome

workflows:
  version: 2
  test:
    jobs:
      - cypress-tests