version: 2.1

jobs:
  cypress-test:
    docker:
      - image: cypress/base:16  # Cypress base image with Node.js
    steps:
      - checkout  # Checkout your repository
      
      # Install project dependencies
      - run:
          name: Install dependencies
          command: npm install
     

      # Ensure Cypress is installed and has execute permissions
      - run:
          name: Install Cypress binary and set permissions
          command: |
            npx cypress install  # Install Cypress
            

      # Run Cypress tests
      - run:
          name: Run Cypress tests
          command: npx cypress run  # Run the tests with npx

workflows:
  version: 2
  test:
    jobs:
      - cypress-test