version: 2.1
jobs:
 cypress-test:
   docker:
     - image: cypress/base:16
   steps:
     - checkout
     - run:
         name: Install dependencies
         command: npm install
     - run:
         name: Install Cypress binary
         command: npx cypress install
     - run:
         name: Run Cypress tests
         command: npx cypress run


workflows:
 version: 2
 test:
   jobs:
     - cypress-test
