version: 2.1

jobs:
  cypress-test:
    docker:
      - image: cypress/base:16  # Cypress base image with Node.js
    steps:
      - checkout  # Checkout your repository
      
      # Install project dependencies
      - run:
          name: Install dependencies
          command: npm install
     
      - run:
          name: Ensure Cypress binary has execute permissions
          command: |
            chmod +x ./node_modules/.bin/cypress 
            

      # Run Cypress tests
      - run:
          name: Run Cypress tests
          command: npx cypress run  # Run the tests with npx

workflows:
  version: 2
  test:
    jobs:
      - cypress-test